# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

# Note

For this homework, you may want to attach sketches as means to explain your ideas. Here is how you can attach images.

![everly1](img/everly7.jpg)

In [10]:
# sample code for Problem 2
import numpy as np

# x[1] corresponds to x2 and x[2] with x3
obj = lambda x: (5*x[1]**2+12*x[1]*x[2]-8*x[1]+10*x[2]**2-14*x[2]+5)
def grad(x):
    return [2*(x[0]-1), 2*(x[1] + 1)]

eps = 1e-3  # termination criterion
x0 = [0., 0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps
x = soln[k]  # start with the initial guess

error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 0.1  # set a fixed step size to start with

# Armijo line search
# def line_search(x):
#     a = 1.  # initialize step size
#     phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  # define phi as a search criterion
#     while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
#         a = 0.5*a
#     return a

while error >= eps:  # keep searching while gradient norm is larger than eps
#     a = line_search(x)
    x = np.array(x) - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
soln  # print the search trajectory

[[0.0, 0.0],
 array([ 0.2, -0.2]),
 array([ 0.36, -0.36]),
 array([ 0.488, -0.488]),
 array([ 0.5904, -0.5904]),
 array([ 0.67232, -0.67232]),
 array([ 0.737856, -0.737856]),
 array([ 0.7902848, -0.7902848]),
 array([ 0.83222784, -0.83222784]),
 array([ 0.86578227, -0.86578227]),
 array([ 0.89262582, -0.89262582]),
 array([ 0.91410065, -0.91410065]),
 array([ 0.93128052, -0.93128052]),
 array([ 0.94502442, -0.94502442]),
 array([ 0.95601953, -0.95601953]),
 array([ 0.96481563, -0.96481563]),
 array([ 0.9718525, -0.9718525]),
 array([ 0.977482, -0.977482]),
 array([ 0.9819856, -0.9819856]),
 array([ 0.98558848, -0.98558848]),
 array([ 0.98847078, -0.98847078]),
 array([ 0.99077663, -0.99077663]),
 array([ 0.9926213, -0.9926213]),
 array([ 0.99409704, -0.99409704]),
 array([ 0.99527763, -0.99527763]),
 array([ 0.99622211, -0.99622211]),
 array([ 0.99697769, -0.99697769]),
 array([ 0.99758215, -0.99758215]),
 array([ 0.99806572, -0.99806572]),
 array([ 0.99845257, -0.99845257]),
 array([ 